---
title: "Introduction to imaginarycss"
author: "George Vega Yon"
date: today
format:
  html:
    toc: true
    toc-depth: 3
    fig-width: 7
    fig-height: 5
vignette: >
  %\VignetteIndexEntry{Introduction to imaginarycss}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/vignette-",
  out.width = "100%",
  warning = FALSE,
  message = FALSE
)
```

# Introduction

The `imaginarycss` package provides tools for analyzing **Cognitive Social Structures** (CSS).

## Basic Usage

```{r basic-example}
library(imaginarycss)

# Simple example
source_ <- c(1, 2, 3, 1) 
target_ <- c(2, 1, 4, 4)
source_ <- c(source_, source_[-1] + 4)
target_ <- c(target_, target_[-1] + 4)

adjmat <- matrix(0L, nrow = 8, ncol = 8)
adjmat[cbind(source_, target_)] <- 1L

graph <- new_barry_graph(adjmat, n = 4)
print(graph)
```

## Key Attributes

```{r attributes}
cat("Network size:", attr(graph, "netsize"), "\n")
cat("Endpoints:", attr(graph, "endpoints"), "\n")
```

## Analysis Functions

```{r analysis}
# Compute reciprocity errors
recip_errors <- count_recip_errors(graph)
print(recip_errors)

# Compute imaginary census
census <- count_imaginary_census(graph)
print(head(census))
```